### ISSUE TITLE
能否支持区域标注，就是绘制多边形

### ISSUE THREAD

**Issue by zuoliang0** [yeye0922/ZoomMarker#10]
https://lbs.amap.com/api/javascript-api/example/mouse-operate-map/mouse-draw-overlayers
类似这种效果

**Comment by yeye0922** [comment]
支持canvas图层，你可以在上面绘制

**Comment by zuoliang0** [comment]
感谢，我已经使用高德，完成了功能，感谢

**Comment by yeye0922** [comment]
好的，祝顺利
