### ISSUE TITLE
删除标记好像有点问题，id对不上

### ISSUE THREAD

**Issue by xiezongzhi** [yeye0922/ZoomMarker#5]
RT

**Comment by yeye0922** [comment]
可以在console截个图看看么

**Comment by xiezongzhi** [comment]
不好意思，应该是我这边报错了，但是还发现一个问题，就是每次缩放过后，图片的大小跟设定min的值不一致，每次缩放到最小图片宽度都不一样

**Comment by xiezongzhi** [comment]
` delta>0?(1+options.rate):(1-options.rate))` 这句的(1-options.rate)有点问题

**Comment by yeye0922** [comment]
感谢提醒，问题已修正，请更新版本0.0.9
