### ISSUE TITLE
鼠标放到A点滑动放大，再将鼠标移到B点滑动缩小，图片的原始位置变化了？请问有办法可以保持原始位置不变吗？

### ISSUE THREAD

**Issue by biankui** [yeye0922/ZoomMarker#7]

**Comment by yeye0922** [comment]
会变化，放大缩小都是以鼠标作为缩放中点的，目前没有接口可以取消，这是什么样的场景需要缩放后位置不变？如果需要我可以加上

**Comment by biankui** [comment]
比如有页面有一块div，要求图片填满这个div, 如果你以鼠标为中心（在左上角放大，在右下角缩小），最后缩放的结果就会导致这个图片只能一部分填充在这个div里面，其他部分hide了

**Comment by yeye0922** [comment]
好的，晚点通过配置添加这个功能

**Comment by biankui** [comment]
我通过zoomMarker_Move方法，监控轮动事件，发现图片尺寸缩小到指定尺寸后重新设置x,y

**Comment by biankui** [comment]
老哥，这个图片缩放插件是我用的体验最好的一个，建议增加zoomMarker方法的init和distory，以便于更好的在页面通过事件调用交互，另外markers建议可以改为可drag

**Comment by yeye0922** [comment]
已经更新至0.1.2版本，缩放锁定可以在调用初始化的时候通过配置zoom_lock: true启用，如

    $('#zoom-marker-img').zoomMarker({
        src: "img/mountain.jpg",
        rate: 0.2,
        width: 400,
        max: 3000,
        markers:[
            {src:"img/marker.svg", x:200, y:200, draggable:false}
        ],
        zoom_lock: true
    });

**Comment by yeye0922** [comment]
另外，标记点可拖动功能也已经添加啦，默认标记点是开启的，也可以在添加标记点的时候配置draggable: false手动关闭拖动功能。有空记得加星呀，多谢~
