### ISSUE TITLE
支持移动端吗？

### ISSUE THREAD

**Issue by wanmen4580** [yeye0922/ZoomMarker#8]
移动端操作的时候，拖动图片，图片会跑偏。

**Comment by yeye0922** [comment]
使用的是什么系统？哪个浏览器？

**Comment by wanmen4580** [comment]
安卓系统，我做的web app里面。

发自我的 iPhone

**Comment by yeye0922** [comment]
是在Android的Webview加载吗？我在安卓机器上用UC和华为内置浏览器查看github的demo，是可以移动的

**Comment by wanmen4580** [comment]
是webview，你可以试着在chrome调试状态，选择ipad pro或者其他的，然后点击拖动，左右是正常的，但是上下就出问题了，注意，操作的时候直接点中向下或向上，您试试看

发自我的 iPhone

**Comment by wanmen4580** [comment]
发自我的 iPhone

**Comment by wanmen4580** [comment]
我发了一段视频，不支持显示呀。

**Comment by yeye0922** [comment]
问题已修复，请更新至0.1.4版本
